---
- name: Stop Cagelab Services
  hosts: all
  gather_facts: false
  tasks:
    - name: Stop services
      ignore_errors: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        scope: user
      loop:
        - theConductor.service
        - cogmoteGO.service
        - obs-fix.service
        - obs.service
        - mediamtx.service
