---
- name: Start Cagelab Services
  hosts: "{{ target | default('cagelab_servers') }}"
  gather_facts: false
  tasks:
    - name: Start services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        scope: user
      loop:
        - cogmoteGO
        - theConductor
        - mediamtx
        - obs
