---
- name: Stop Cagelab Services
  hosts: "{{ target | default('cagelab_servers') }}"
  gather_facts: false
  tasks:
    - name: Stop services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        scope: user
      loop:
        - theConductor.service
        - cogmoteGO.service
        - obs-fix.service
        - obs.service
        - mediamtx.service
