---
- name: Start Cagelab Services
  hosts: all
  gather_facts: false
  tasks:
    - name: Start services
      ignore_errors: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        scope: user
      loop:
        - cogmoteGO
        - theConductor
        - mediamtx
        - obs
